//! SeaORM Entity. Generated by sea-orm-codegen 0.10.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "catalog")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::namespace::Entity")]
    Namespace,
    #[sea_orm(has_many = "super::iceberg_table::Entity")]
    IcebergTable,
}

impl Related<super::namespace::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Namespace.def()
    }
}

impl Related<super::iceberg_table::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IcebergTable.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
